---
- name: download / updates cpp client
  sudo: true
  # the official ansible docker module does not have the option to just pull the image, it will also run it
  shell: docker pull {{ g_docker_hub_image['cpp'] }} 
  register: docker_pull_out
  changed_when: '"Downloaded newer image" in docker_pull_out.stdout'
  tags:

- name: download / updates latest Go clients base via docker
  sudo: true
  # the official ansible docker module does not have the option to just pull the image, it will also run it
  shell: docker pull {{ g_docker_hub_image['go'] }} 
  register: docker_pull_out
  changed_when: '"Downloaded newer image" in docker_pull_out.stdout'

- name: Prepare updates to geth for system testing
  copy: src=../files/docker-go-clean dest=/tmp

- name: Build updated geth image for system testing locally 
  sudo: yes
  docker_image:
    path: /tmp/docker-go-clean
    name: "{{ g_docker_clean_image['go'] }}"
    state: build
