---
- name: Start bootstrapping node (go)
  sudo: yes
  docker: 
    image: "{{ g_docker_clean_image['go'] }}"  
    expose:   
      - 30303/tcp
      - 30303/udp
    ports:    
      - 30303:30303/tcp
      - 30303:30303/udp
    # the proper way to start a server would be to use --bootnodes "" but they are not escaped correctly
    command:  --nodekeyhex={{ boot0_private_key }} --port=30303 --bootnodes enode://{{ g_boot0_public_key }}@10.0.0.0:10000
