---

- name: Provision EC2 nodes
  hosts: localhost
  gather_facts: false
  roles:
      - common

  tasks:
      # TODO is should be possible to include this without the full path, but it isn't
      - include: roles/common/tasks/startup_ec2.yml
