---
# Effectively lifted from the Ansible documentation on EC2:
# http://docs.ansible.com/ec2_module.html

- name: Provision an EC2 node
  hosts: localhost
  gather_facts: False
  vars:
      instance_type: t2.micro
      security_group: system-testing # this is how all hosts will be identified
      image: ami-9eaa1cf6 
      region: us-east-1
      keypair: system-testing

  tasks:
      - include: tasks/startup_ec2.yml

#      - name: Add instance to local host group
#        # local_action: add_host hostname={{ item.public_ip }} groupname=launched
#        local_action: lineinfile dest="./hosts" regexp="{{ item.public_dns_name }}" insertafter="[launched]" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
#        with_items: ec2.instances
        #"

#      - name: Wait for SSH to come up
#        local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
#        with_items: ec2.instances

        #  - name: With the newly provisioned EC2 node configure that thing
        #    hosts: launched # This uses the hosts that we put into the in-memory hosts repository with the add_host module.
        #    sudo: yes # On EC2 nodes, this is automatically passwordless. 
        #    remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
        #    gather_facts: True  #We need to re-enable this, as we turned it off earlier.
        #    roles:
        #      - common
        #      - redis
        #      - nginx
        #      - zeromq
        #      - deploy_thingy
      # These are the same roles as we configured in the 'Parallax/example' playbook, except they've been symlinked into this one.
