---
- name: Start ethereum python client 
  docker: 
      image: sveneh/pyethereum-develop 
      ports: 30303:30303
      
      # parameters given to client 
      command: --logging :debug --log_json 1 --remote {{ bootstrap_ip }} --mining {{ mining_cpu_percentage }} --peers {{ req_num_peers }}

- name: Get the docker container id
  # ansible docker module does not support this, therefore shell
  shell: docker ps --latest=true --quiet=true 
  register: docker_id

- name: Log docker output to elarch
  # fire and forget, don't wait to finish, run for one day
  async: 86400
  poll: 0
  # again, ansible docker module does not support logs
  # pyethereum wrongly logs to stderr
  shell: docker logs --follow=true {{ docker_id.stdout }} 2>&1 | {{ repo_path }}/logging/teees.py {{ elarch_ip }}
