---
- name: start ec2 instance for bootstrapping node
  ec2:  
    group: ["{{ security_group }}"]
    instance_type: "{{ instance_type }}" 
    image: "{{ image }}" 
    wait: true 
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    instance_tags:
        Name: boot
        Role: bootstrap
    count_tag: 
        Name: boot 
    exact_count: 1
    user_data: "#include https://get.docker.com"
#  register: ec2

#  checking for ssh not working yet
# - include: add_host.yml

- name: start new ec2 instances for clients
  ec2:  
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}" 
    image: "{{ image }}" 
    wait: true 
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    instance_tags:
        Name: "{{ item }}"
        Role: client
        Impl: python
    count_tag: # exactly one instance with the given name
        Name: "{{ item }}"
    exact_count: 1
    user_data: "#include https://get.docker.com"
  with_sequence: start=1 end={{ total_no_clients }} format=client-%02x


- name: start ec2 instance for elasticsearch node
  ec2:  
    group: ["{{ security_group }}", elarch]
    instance_type: "{{ instance_type }}" 
    image: "{{ image }}" 
    wait: true 
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    instance_tags:
        Name: elarch
        Role: logserver
    count_tag: 
        Name: elarch 
    exact_count: 1
    user_data: "#include https://get.docker.com"
