---

- name: Start ethereum docker clients
  hosts: security_group_system-testing # this is provided by ec2.py
  remote_user: ubuntu 
  sudo: yes
  gather_facts: false
  roles:
      - common

  tasks:
      # TODO is should be possible to include this without the full path, but it isn't
      - include: roles/common/tasks/docker-ansible.yml
      - include: roles/common/tasks/docker.yml
