---
# does not delete any older image, to clean those up, delete them from AWS console
- name: saves instance state to new AMI
  local_action: ec2_ami
        instance_id="{{ ansible_ec2_instance_id }}"
        region="{{ ec2_region }}"
        name="ST {{ type }} {{ ansible_date_time.epoch }}"
        description="System Testing - automatically saved image from running host"
        wait=yes
  register: amiout

- name: store AMI id in file
  local_action: replace
    dest=roles/ec2/vars/main.yml
    regexp="(?s)(ec2_image_clone_{{ type }}.*{{ ec2_region }}.\s*)ami-\w*"
    replace="\1{{ amiout.image_id }}"
