---
- name: Setup client nodes
  hosts: tag_Role_client
  remote_user: ubuntu
  gather_facts: false
  roles:
      - docker_install
      - common
      - clients

  tasks:
      - include: roles/clients/tasks/setup.yml
