---
- name: Starts a client with parameters supplied from inventory file
  hosts: client_start_group
  remote_user: ubuntu
  gather_facts: false
  roles:
      - clients

  tasks:
      - include: roles/clients/tasks/start.yml
