---
- name: Prepare a already downloaded client for use
  hosts: tag_Role_ST-client-host
  remote_user: ubuntu
  gather_facts: false
  roles:
      - clients

  tasks:
      - include: roles/clients/tasks/prepare.yml
      - include: roles/clients/tasks/ethash.yml
