---
- name: Setup client nodes
  hosts: tag_Role_ST-client-host
  remote_user: ubuntu
  gather_facts: false
  roles:
      - clients

  tasks:
    - include: roles/clients/tasks/docker-pull.yml
    - include: roles/clients/tasks/prepare.yml
