---
- name: Reset state on all clients 
  hosts: tag_Role_ST-client-host
  remote_user: ubuntu
  gather_facts: false
  roles:
    - clients
  
  tasks:
    - include: roles/clients/tasks/reset.yml
      vars:

        target_client_impl: 
          - go
          - cpp
