---
- name: Provision EC2 instances from previously saved state
  hosts: localhost
  gather_facts: false
  roles:
      - ec2 

  tasks:
      - include: roles/ec2/tasks/setup.yml
        vars:
          ami_client: "{{ ec2_image_clone_client[ec2_region] }}"
