---
- name: Terminate all client instances except the log server
  hosts: security_group_system-testing:!tag_Name_ST-elarch # this is provided by ec2.py
  remote_user: ubuntu 
  gather_facts: false
  roles:
      - ec2

  tasks:
      - include: roles/ec2/tasks/terminate.yml
