---
- name: Setup client nodes
  hosts: tag_Name_pythereum
  remote_user: ubuntu
  gather_facts: false
  roles:
      - common
      - clients

  tasks:
      - include: roles/clients/tasks/setup.yml
