---
# default config for ec2 instances

instance_type:      t2.micro
security_group:     system-testing 
image:              ami-9eaa1cf6 
region:             us-east-1
keypair:            system-testing

total_no_clients:   5
