---
- name: Ensure that ethash folder exists on host
  sudo: true
  file: name=/mnt/docker-eth state=directory

- name: create the ethash (dag) from geth
  sudo: true
  async: 1000
  poll: 20
  # ethhash is expected to be in /tmp/dag
  shell: docker run --rm --volume=/mnt/docker-eth:/tmp {{ g_docker_work_image['go'] }} makedag
