---
# prepararions for the clients before they are usable

- name: add the work tag to the image for later reference
  sudo: true
  shell: docker tag --force $(docker history --quiet {{ g_docker_clean_image[item] }} | head --lines=1) {{ g_docker_work_image[item] }}
  with_items: 
    - go
    - cpp
    - python


- include: account.yml

