---
- include: stop.yml

- name: remove all containers from host
  shell: docker rm --force $(docker ps --all --quiet)
  ignore_errors: true

- name: remove all work images from host
  shell: docker rmi {{ g_docker_work_image[item] }}
  with_items:
    - go
    - cpp
    - python 
  ignore_errors: true

- name: remove all leftover untagged images from host
  shell: docker rmi -f $(docker images | grep "<none>" | awk "{print \$3}")
  ignore_errors: true

- include: prepare.yml
