---
- name: checkout git system-testing repo (for teees.py)
  git:
      repo: https://github.com/ethereum/system-testing.git
      dest: "{{ repo_path }}"
        
- name: install logging framework dependencies
  sudo: true
  pip:
    name: elasticsearch
    version: 0.4.5 

- include: docker-pull.yml

- include: prepare.yml

- include: ethash.yml
