---
# this will only work when missing parameters are injected into the inventory file.

- name: start clients with parameters from inventory file 
  docker:
    image:  "{{ g_docker_work_image[item[0]] }}"  
    # container id example: docker_container_go_004
    name:   "{{ docker_container_base_string ~ '_' ~ item[0] ~ '_' ~ item[1] }}"
    expose:
      - "{{ ext_port[item[0]].rpc }}/tcp"
      - "{{ ext_port[item[0]].p2p }}/udp"
      - "{{ ext_port[item[0]].p2p }}/tcp"
    ports:
      - "{{ ext_port[item[0]].rpc + item[1]|int }}:{{ ext_port[item[0]].rpc }}/tcp"
      - "{{ ext_port[item[0]].p2p + item[1]|int }}:{{ ext_port[item[0]].p2p }}/udp"
      - "{{ ext_port[item[0]].p2p + item[1]|int }}:{{ ext_port[item[0]].p2p }}/tcp"
    # uses pre-calculated dag, only tested with go client
    volumes: "/tmp/docker-eth:/tmp"
    command: "{{ docker_run_args[item[0]] }}"
  with_nested:
    - target_client_impl
    - target_client_no
  tags:
    - go
    - cpp
    - python

- name: ensure clients run, check cmd-line parameters if this fails
  shell: docker ps 
  register: docker_ps_out
  failed_when: not docker_container_base_string ~ '_' ~ item[0] ~ '_' ~ item[1] in docker_ps_out.stdout
  with_nested:
    - target_client_impl
    - target_client_no
  tags:
    - go
    - cpp
    - python

# TODO! This only works with the first implementation! No loop support w/ async
- name: Forward go logfiles with parameters from inventory file
  # fire and forget, don't wait to finish, run for one day
  async: 86400
  poll: 0
  # again, ansible docker module does not support logs
  shell: docker logs --follow=true {{ docker_container_base_string ~ '_go_000' }} 2>&1 | {{ repo_path }}/logging/teees.py {{ docker_tee_args['go'] }} 
  register: log_runner_go
  tags:
    - go

# TODO! This only works with the first implementation! No loop support w/ async
- name: Forward cpp logfiles with parameters from inventory file
  # fire and forget, don't wait to finish, run for one day
  async: 86400
  poll: 0
  # again, ansible docker module does not support logs
  shell: docker logs --follow=true {{ docker_container_base_string ~ '_cpp_000' }} 2>&1 | {{ repo_path }}/logging/teees.py {{ docker_tee_args['cpp'] }} 
  register: log_runner_cpp
  tags:
    - cpp 

# - name: Forward go logfiles with parameters from inventory file
  # daemonize, in ansible only possible via 'async' but that does not work with 'with_nested'
  # use workaround instead: http://superuser.com/questions/870871/run-a-remote-script-application-in-detached-mode-in-ansible
  # TODO: This causes 100% CPU usage, so maybe that's not the way to go
  #   shell: ( ( nohup docker logs --follow {{ docker_container_base_string ~ '_' ~ item[0] ~ '_' ~ item[1] }}  docker_container_go_000 2>&1 | {{ repo_path }}/logging/teees.py {{ docker_tee_args[item[0]] }} ) & ) 
  #  with_nested:
  #  - target_client_impl
  #  - target_client_no
